### ISSUE TITLE
Platform: Toolbar comment button cut in half on small editor width

### ISSUE THREAD

**Issue by Sebastian-ubs** [BiblioNexus-Foundation/scripture-editors#126]
On a small editor width the other toolbar controls (back, forward, style) move up a bit to make space for a scrollbar, whereas the comment button stays and so is cut in half / overlayed by the horizontal scrollbar:
![grafik](https://github.com/BiblioNexus-Foundation/scripture-editors/assets/141921979/df085fb1-b139-4264-b5ed-f3baad1c5697)

In Firefox this is not seen, as Firefox uses a smaller scrollbar.
In Chrome and Electron it is visible like can be seen above - this screenshot is from the [scripture-editor codesandbox](https://codesandbox.io/p/github/BiblioNexus-Foundation/scripture-editors/main?file=%2FREADME.md)

Besides with a small editor width this also happens in a wider editor, when there is a long style name selected in the dropdown, which increases its width.

**Comment by irahopkinson** [comment]
@Sebastian-ubs thanks for trying things out in the editor. Any thoughts on what it should do instead? And/or how to fix it?

**Comment by Sebastian-ubs** [comment]
Not sure how those other ui elements shrink / re-arrange, but I would expect the comment button to behave similar.

**Comment by Sebastian-ubs** [comment]
In general the toolbar should ideally never need to show vertical scrollbars, but adapt to the available width by
- defining the dropdown width not based on its content, but shrinking / growing according to available space
- define a reasonable min-width and if smaller, hide controls in an overflow menu

**Comment by Sebastian-ubs** [comment]
a working solution seems to be
```css
    .toolbar-item.block-controls {
      max-width: calc(100% - 140px);
      .icon.block-marker.nb {
        min-width: 20px;
      }
      .chevron-down {
        min-width: 16px;
      }
    }
```
Which of course is not very flexible with the hard coded 140px, but does its job for now.
